// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/news/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/news/:id";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/news-detail.tsx": {
    id: "routes/news-detail";
    page: "/news/:id";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/home": typeof import("./src/app/./routes/home.tsx");
  "routes/news-detail": typeof import("./src/app/./routes/news-detail.tsx");
};